language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script: pytest
deploy:
  provider: gae
  keyfile: travis.json.enc
  project: statbotics-io-276522
  verbosity: debug
  config: app.yaml
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_7e3b9f3f674f_key -iv $encrypted_7e3b9f3f674f_iv
  -in travis.json.enc -out travis.json -d
