language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

script: pytest

deploy:
  provider: gae
  keyfile: travis.json.enc
  project: statbotics-io-276522
  config: app.yaml
  on: master
