[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.flake8]
max-line-length = 88
max-complexity = 100
select = B,C,E,F,W,T4,B9
ignore = E203, E266, E501, W503, F403, F401

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = True
known_third_party = ["classes", "constants", "event_pred", "google", "helper", "models", "numpy", "pandas", "process", "requests", "scipy", "sqlalchemy", "tba"]
