# [START django_app]
runtime: python37

#smallest instance class
instance_class: F2

#prevents creating additional instances
automatic_scaling:
  max_instances: 1

#set to minimums
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
# [END django_app]

env_variables:
  LOCAL_DB: false
