service: data
runtime: python37
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app

instance_class: F1

# exactly one instance
automatic_scaling:
  max_instances: 2

#set to minimums
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  LOCAL_DB: false
