# TODO: further consolidate, ensure year-over-year consistency

key_to_name = {
    2016: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "defenses_rp",
        "rp_2": "tower_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_1": "auto_reach_points",
        "comp_2": "auto_crossing_points",
        "comp_3": "auto_low_boulders",
        "comp_4": "auto_high_boulders",
        "comp_5": "teleop_crossing_points",
        "comp_6": "teleop_low_boulders",
        "comp_7": "teleop_high_boulders",
        "comp_8": "challenge_points",
        "comp_9": "scale_points",
        "comp_10": "defenses",
        "comp_11": "boulders",
    },
    2017: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "rotor_rp",
        "rp_2": "kpa_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_1": "auto_mobility_points",
        "comp_2": "auto_fuel_low",
        "comp_3": "auto_fuel_high",
        "comp_4": "auto_rotor_points",
        "comp_5": "teleop_fuel_low",
        "comp_6": "teleop_fuel_high",
        "comp_7": "teleop_rotor_points",
        "comp_8": "takeoff_points",
        "comp_9": "kpa",
        "comp_10": "gears",
    },
    2018: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "auto_rp",
        "rp_2": "climb_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_1": "auto_run_points",
        "comp_2": "auto_switch_secs",
        "comp_3": "auto_scale_secs",
        "comp_4": "teleop_switch_secs",
        "comp_5": "teleop_scale_secs",
        "comp_6": "vault_points",
        "comp_7": "auto_scale_power",
        "comp_8": "teleop_scale_power",
        "comp_9": "switch_power",
        "comp_10": "scale_power",
    },
    2019: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "rocket_rp",
        "rp_2": "hab_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_1": "sandstorm_points",
        "comp_2": "bay_hatch_pieces",
        "comp_3": "bay_cargo_pieces",
        "comp_4": "rocket_hatch_low_pieces",
        "comp_5": "rocket_hatch_mid_pieces",
        "comp_6": "rocket_hatch_high_pieces",
        "comp_7": "rocket_cargo_low_pieces",
        "comp_8": "rocket_cargo_mid_pieces",
        "comp_9": "rocket_cargo_high_pieces",
        "comp_10": "hab_climb_points",
        "comp_11": "rocket_pieces",
        "comp_12": "bay_pieces",
    },
    2020: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "cells_rp",
        "rp_2": "climb_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_1": "auto_init_line_points",
        "comp_2": "auto_cells_bottom",
        "comp_3": "auto_cells_outer",
        "comp_4": "auto_cells_inner",
        "comp_5": "teleop_cells_bottom",
        "comp_6": "teleop_cells_outer",
        "comp_7": "teleop_cells_inner",
        "comp_8": "control_panel_points",
        "comp_9": "endgame_points",
        "comp_10": "cells",
    },
    2021: {},
    2022: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "cargo_rp",
        "rp_2": "hangar_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_1": "auto_taxi_points",
        "comp_2": "auto_cargo_lower",
        "comp_3": "auto_cargo_upper",
        "comp_4": "teleop_cargo_lower",
        "comp_5": "teleop_cargo_upper",
        "comp_6": "endgame_points",
        "comp_7": "cargo",
    },
    2023: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "links_rp",
        "rp_2": "activation_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_1": "auto_mobility_points",
        "comp_2": "auto_charge_station_points",
        "comp_3": "auto_bottom_cubes",
        "comp_4": "auto_bottom_cones",
        "comp_5": "auto_middle_cubes",
        "comp_6": "auto_middle_cones",
        "comp_7": "auto_top_cubes",
        "comp_8": "auto_top_cones",
        "comp_9": "teleop_bottom_cubes",
        "comp_10": "teleop_bottom_cones",
        "comp_11": "teleop_middle_cubes",
        "comp_12": "teleop_middle_cones",
        "comp_13": "teleop_top_cubes",
        "comp_14": "teleop_top_cones",
        "comp_15": "links",
        "comp_16": "endgame_charge_station_points",
        "comp_17": "endgame_park_points",
        "comp_18": "charge_station_points",
    },
}


all_keys = {
    2002: ["no_foul_points"],
    2003: ["no_foul_points"],
    2004: ["no_foul_points"],
    2005: ["no_foul_points"],
    2006: ["no_foul_points"],
    2007: ["no_foul_points"],
    2008: ["no_foul_points"],
    2009: ["no_foul_points"],
    2010: ["no_foul_points"],
    2011: ["no_foul_points"],
    2012: ["no_foul_points"],
    2013: ["no_foul_points"],
    2014: ["no_foul_points"],
    2015: ["no_foul_points"],
    2016: [
        "no_foul_points",
        "auto_points",
        "teleop_points",
        "endgame_points",
        "rp_1",
        "rp_2",
        "tiebreaker_points",
        "auto_reach_points",
        "auto_crossing_points",
        "auto_low_boulders",
        "auto_high_boulders",
        "teleop_crossing_points",
        "teleop_low_boulders",
        "teleop_high_boulders",
        "challenge_points",
        "scale_points",
        "defenses",
        "boulders",
    ],
    2017: [
        "no_foul_points",
        "auto_points",
        "teleop_points",
        "endgame_points",
        "rp_1",
        "rp_2",
        "tiebreaker_points",
        "auto_mobility_points",
        "auto_fuel_low",
        "auto_fuel_high",
        "auto_rotor_points",
        "teleop_fuel_low",
        "teleop_fuel_high",
        "teleop_rotor_points",
        "takeoff_points",
        "kpa",
        "gears",
    ],
    2018: [
        "no_foul_points",
        "auto_points",
        "teleop_points",
        "endgame_points",
        "rp_1",
        "rp_2",
        "tiebreaker_points",
        "auto_run_points",
        "auto_switch_secs",
        "auto_scale_secs",
        "teleop_switch_secs",
        "teleop_scale_secs",
        "vault_points",
        "auto_scale_power",
        "switch_power",
        "scale_power",
        "opp_switch_power",
    ],
    2019: [
        "no_foul_points",
        "auto_points",
        "teleop_points",
        "endgame_points",
        "rp_1",
        "rp_2",
        "tiebreaker_points",
        "sandstorm_points",
        "bay_hatch",
        "bay_cargo",
        "rocket_hatch_low",
        "rocket_hatch_mid",
        "rocket_hatch_top",
        "rocket_cargo_low",
        "rocket_cargo_mid",
        "rocket_cargo_top",
        "hab_climb_points",
        "rocket",
        "pieces",
    ],
    2020: [
        "no_foul_points",
        "auto_points",
        "teleop_points",
        "endgame_points",
        "rp_1",
        "rp_2",
        "tiebreaker_points",
        "auto_init_line_points",
        "auto_cells_bottom",
        "auto_cells_outer",
        "auto_cells_inner",
        "teleop_cells_bottom",
        "teleop_cells_outer",
        "teleop_cells_inner",
        "control_panel_points",
        "endgame_points",
        "cells",
    ],
    2021: ["no_foul_points"],
    2022: [
        "no_foul_points",
        "auto_points",
        "teleop_points",
        "endgame_points",
        "rp_1",
        "rp_2",
        "tiebreaker_points",
        "auto_taxi_points",
        "auto_cargo_lower",
        "auto_cargo_upper",
        "teleop_cargo_lower",
        "teleop_cargo_upper",
        "endgame_points",
        "cargo",
    ],
    2023: [
        "no_foul_points",
        "auto_points",
        "teleop_points",
        "endgame_points",
        "rp_1",
        "rp_2",
        "tiebreaker_points",
        "auto_mobility_points",
        "auto_charge_station_points",
        "auto_bot_cubes",
        "auto_bot_cones",
        "auto_mid_cubes",
        "auto_mid_cones",
        "auto_top_cubes",
        "auto_top_cones",
        "teleop_bot_cubes",
        "teleop_bot_cones",
        "teleop_mid_cubes",
        "teleop_mid_cones",
        "teleop_top_cubes",
        "teleop_top_cones",
        "links",
        "endgame_charge_station_points",
        "endgame_park_points",
        "charge_station_points",
    ],
}
