countries = {
    "united states of america": "USA",
    "united states": "USA",
    "america": "USA",
    "usa": "USA",
    "canada": "Canada",
    "turkey": "Turkey",
    "israel": "Israel",
    "china": "China",
    "mexico": "Mexico",
    "australia": "Australia",
    "brazil": "Brazil",
    "chinese taipei": "Chinese Taipei",
    "netherlands": "Netherlands",
    "chile": "Chile",
    "united kingdom": "United Kingdom",
    "uk": "United Kingdom",
    "colombia": "Colombia",
    "japan": "Japan",
    "poland": "Poland",
    "india": "India",
    "switzerland": "Switzerland",
}

USA = {
    "alabama": "AL",
    "alaska": "AK",
    "american samoa": "AS",
    "arizona": "AZ",
    "arkansas": "AR",
    "california": "CA",
    "colorado": "CO",
    "connecticut": "CT",
    "delaware": "DE",
    "district of columbia": "DC",
    "florida": "FL",
    "georgia": "GA",
    "guam": "GU",
    "hawaii": "HI",
    "idaho": "ID",
    "illinois": "IL",
    "indiana": "IN",
    "iowa": "IA",
    "kansas": "KS",
    "kentucky": "KY",
    "louisiana": "LA",
    "maine": "ME",
    "maryland": "MD",
    "massachusetts": "MA",
    "michigan": "MI",
    "minnesota": "MN",
    "mississippi": "MS",
    "missouri": "MO",
    "montana": "MT",
    "nebraska": "NE",
    "nevada": "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    "north carolina": "NC",
    "north dakota": "ND",
    "northern mariana islands": "MP",
    "ohio": "OH",
    "oklahoma": "OK",
    "oregon": "OR",
    "pennsylvania": "PA",
    "puerto Rico": "PR",
    "rhode island": "RI",
    "south carolina": "SC",
    "south dakota": "SD",
    "tennessee": "TN",
    "texas": "TX",
    "utah": "UT",
    "vermont": "VT",
    "virgin islands": "VI",
    "virginia": "VA",
    "washington": "WA",
    "west virginia": "WV",
    "wisconsin": "WI",
    "wyoming": "WY",
}

Canada = {
    "newfoundland": "NL",
    "prince edward island": "PE",
    "nova scotia": "NS",
    "new brunswick": "NB",
    "québec": "QC",
    "quebec": "QC",
    "ontario": "ON",
    "manitoba": "MB",
    "saskatchewan": "SK",
    "alberta": "AB",
    "british columbia": "BC",
    "yukon": "YT",
    "northwest territories": "NT",
    "nunavut": "NU",
}

districts = {
    "mar": "fma",
    "fma": "fma",
    "nc": "fnc",
    "fnc": "fnc",
    "tx": "fit",
    "fit": "fit",
    "in": "fin",
    "fin": "fin",
    "fim": "fim",
    "ne": "ne",
    "chs": "chs",
    "ont": "ont",
    "pnw": "pnw",
    "pch": "pch",
    "isr": "isr",
}

team_metrics = [
    "team",
    "norm_epa",
    "norm_epa_recent",
    "norm_epa_mean",
    "norm_epa_max",
    "wins",
    "losses",
    "ties",
    "count",
    "winrate",
]

year_metrics = [
    "year",
    "quals_count",
    "elims_count",
    "champs_count",
    "count",
    "epa_quals_acc",
    "epa_quals_mse",
    "epa_elims_acc",
    "epa_elims_mse",
    "epa_champs_acc",
    "epa_champs_mse",
    "epa_acc",
    "epa_mse",
    "rp_1_acc",
    "rp_1_mse",
    "rp_1_champs_acc",
    "rp_1_champs_mse",
    "rp_2_acc",
    "rp_2_mse",
    "rp_2_champs_acc",
    "rp_2_champs_mse",
]

team_year_metrics = [
    "elo_start",
    "-elo_start",
    "elo_pre_champs",
    "-elo_pre_champs",
    "elo_end",
    "-elo_end",
    "elo_mean",
    "-elo_mean",
    "elo_max",
    "-elo_max",
    "elo_diff",
    "-elo_diff",
    "opr",
    "-opr",
    "opr_auto",
    "-opr_auto",
    "opr_1",
    "-opr_1",
    "opr_2",
    "-opr_2",
    "opr_endgame",
    "-opr_endgame",
    "opr_fouls",
    "-opr_fouls",
    "opr_no_fouls",
    "-opr_no_fouls",
    "ils_1",
    "-ils_1",
    "ils_2",
    "-ils_2",
]

event_metrics = [
    "time",
    "-time",
    "elo_top8",
    "-elo_top8",
    "elo_top24",
    "-elo_top24",
    "elo_mean",
    "-elo_mean",
    "opr_top8",
    "-opr_top8",
    "opr_top24",
    "-opr_top24",
    "opr_mean",
    "-opr_mean",
]

team_event_metrics = [
    "time",
    "-time",
    "elo_start",
    "-elo_start",
    "elo_pre_playoffs",
    "-elo_pre_playoffs",
    "elo_end",
    "-elo_end",
    "elo_mean",
    "-elo_mean",
    "elo_max",
    "-elo_max",
    "elo_diff",
    "-elo_diff",
    "opr_start",
    "-opr_start",
    "opr_end",
    "-opr_end",
    "ils_1",
    "-ils_1",
    "ils_2",
    "-ils_2",
]
