countries = {
    "united states of america": "USA",
    "united states": "USA",
    "america": "USA",
    "usa": "USA",
    "canada": "Canada",
    "turkey": "Türkiye",
    "turkiye": "Türkiye",
    "türkiye": "Türkiye",
    "israel": "Israel",
    "china": "China",
    "mexico": "Mexico",
    "australia": "Australia",
    "brazil": "Brazil",
    "chinese taipei": "Chinese Taipei",
    "netherlands": "Netherlands",
    "chile": "Chile",
    "united kingdom": "United Kingdom",
    "uk": "United Kingdom",
    "colombia": "Colombia",
    "japan": "Japan",
    "poland": "Poland",
    "india": "India",
    "switzerland": "Switzerland",
}

USA = {
    "alabama": "AL",
    "alaska": "AK",
    "american samoa": "AS",
    "arizona": "AZ",
    "arkansas": "AR",
    "california": "CA",
    "colorado": "CO",
    "connecticut": "CT",
    "delaware": "DE",
    "district of columbia": "DC",
    "florida": "FL",
    "georgia": "GA",
    "guam": "GU",
    "hawaii": "HI",
    "idaho": "ID",
    "illinois": "IL",
    "indiana": "IN",
    "iowa": "IA",
    "kansas": "KS",
    "kentucky": "KY",
    "louisiana": "LA",
    "maine": "ME",
    "maryland": "MD",
    "massachusetts": "MA",
    "michigan": "MI",
    "minnesota": "MN",
    "mississippi": "MS",
    "missouri": "MO",
    "montana": "MT",
    "nebraska": "NE",
    "nevada": "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    "north carolina": "NC",
    "north dakota": "ND",
    "northern mariana islands": "MP",
    "ohio": "OH",
    "oklahoma": "OK",
    "oregon": "OR",
    "pennsylvania": "PA",
    "puerto Rico": "PR",
    "rhode island": "RI",
    "south carolina": "SC",
    "south dakota": "SD",
    "tennessee": "TN",
    "texas": "TX",
    "utah": "UT",
    "vermont": "VT",
    "virgin islands": "VI",
    "virginia": "VA",
    "washington": "WA",
    "west virginia": "WV",
    "wisconsin": "WI",
    "wyoming": "WY",
}

Canada = {
    "newfoundland": "NL",
    "prince edward island": "PE",
    "nova scotia": "NS",
    "new brunswick": "NB",
    "québec": "QC",
    "quebec": "QC",
    "ontario": "ON",
    "manitoba": "MB",
    "saskatchewan": "SK",
    "alberta": "AB",
    "british columbia": "BC",
    "yukon": "YT",
    "northwest territories": "NT",
    "nunavut": "NU",
}

districts = {
    "ca": "ca",
    "chs": "fch",
    "fch": "fch",
    "fim": "fim",
    "fin": "fin",
    "fit": "fit",
    "fma": "fma",
    "fnc": "fnc",
    "fsc": "fsc",
    "in": "fin",
    "isr": "isr",
    "mar": "fma",
    "nc": "fnc",
    "ne": "ne",
    "ont": "ont",
    "pch": "pch",
    "pnw": "pnw",
    "tx": "fit",
    "win": "win",
}

team_metrics = [
    "team",
    "norm_epa",
    "norm_epa_recent",
    "norm_epa_mean",
    "norm_epa_max",
    "wins",
    "losses",
    "ties",
    "count",
    "winrate",
]

year_metrics = [
    "year",
    "quals_count",
    "elims_count",
    "champs_count",
    "count",
    "epa_quals_acc",
    "epa_quals_mse",
    "epa_elims_acc",
    "epa_elims_mse",
    "epa_champs_acc",
    "epa_champs_mse",
    "epa_acc",
    "epa_mse",
    "rp_1_acc",
    "rp_1_mse",
    "rp_1_champs_acc",
    "rp_1_champs_mse",
    "rp_2_acc",
    "rp_2_mse",
    "rp_2_champs_acc",
    "rp_2_champs_mse",
    "rp_3_acc",
    "rp_3_mse",
    "rp_3_champs_acc",
    "rp_3_champs_mse",
]

team_year_metrics = [
    "team",
    "year",
    "epa_start",
    "epa_pre_champs",
    "epa_end",
    "epa_mean",
    "epa_max",
    "epa_diff",
    "auto_epa_start",
    "auto_epa_pre_champs",
    "auto_epa_end",
    "auto_epa_mean",
    "auto_epa_max",
    "teleop_epa_start",
    "teleop_epa_pre_champs",
    "teleop_epa_end",
    "teleop_epa_mean",
    "teleop_epa_max",
    "endgame_epa_start",
    "endgame_epa_pre_champs",
    "endgame_epa_end",
    "endgame_epa_mean",
    "endgame_epa_max",
    "rp_1_epa_start",
    "rp_1_epa_pre_champs",
    "rp_1_epa_end",
    "rp_1_epa_mean",
    "rp_1_epa_max",
    "rp_2_epa_start",
    "rp_2_epa_pre_champs",
    "rp_2_epa_end",
    "rp_2_epa_mean",
    "rp_2_epa_max",
    "rp_3_epa_start",
    "rp_3_epa_pre_champs",
    "rp_3_epa_end",
    "rp_3_epa_mean",
    "rp_3_epa_max",
    "unitless_epa_end",
    "norm_epa_end",
    "wins",
    "losses",
    "ties",
    "count",
    "winrate",
    "total_epa_rank",
    "country_epa_rank",
    "state_epa_rank",
    "district_epa_rank",
]

event_metrics = [
    "time",
    "year",
    "type",
    "week",
    "qual_matches",
    "epa_max",
    "epa_top8",
    "epa_top24",
    "epa_mean",
    "epa_sd",
    "epa_acc",
    "epa_mse",
    "rp_1_acc",
    "rp_1_mse",
    "rp_2_acc",
    "rp_2_mse",
    "rp_3_acc",
    "rp_3_mse",
]

team_event_metrics = [
    "team",
    "year",
    "type",
    "week",
    "epa_start",
    "epa_pre_elim",
    "epa",
    "epa_pre_playoffs",
    "epa_end",
    "epa_mean",
    "epa_max",
    "auto_epa",
    "auto_epa_end",
    "auto_epa_mean",
    "auto_epa_max",
    "teleop_epa",
    "teleop_epa_end",
    "teleop_epa_mean",
    "teleop_epa_max",
    "endgame_epa",
    "endgame_epa_end",
    "endgame_epa_mean",
    "endgame_epa_max",
    "rp_1_epa",
    "rp_1_epa_end",
    "rp_1_epa_mean",
    "rp_1_epa_max",
    "rp_2_epa",
    "rp_2_epa_end",
    "rp_2_epa_mean",
    "rp_2_epa_max",
    "rp_3_epa",
    "rp_3_epa_end",
    "rp_3_epa_mean",
    "rp_3_epa_max",
    "unitless_epa",
    "norm_epa",
    "wins",
    "losses",
    "ties",
    "count",
    "winrate",
    "qual_wins",
    "qual_losses",
    "qual_ties",
    "qual_count",
    "rps",
    "rps_per_match",
    "rank",
    "num_teams",
]

team_event_metric_aliases = {
    "epa_pre_playoffs": "epa_pre_elim",
    "epa_end": "epa",
    "auto_epa_end": "auto_epa",
    "teleop_epa_end": "teleop_epa",
    "endgame_epa_end": "endgame_epa",
    "rp_1_epa_end": "rp_1_epa",
    "rp_2_epa_end": "rp_2_epa",
    "rp_3_epa_end": "rp_3_epa",
}

match_metrics = [
    "time",
    "year",
    "set_number",
    "match_number",
    "red_epa_sum",
    "red_auto_epa_sum",
    "red_teleop_epa_sum",
    "red_endgame_epa_sum",
    "red_rp_1_epa_sum",
    "red_rp_2_epa_sum",
    "red_rp_3_epa_sum",
    "blue_epa_sum",
    "blue_auto_epa_sum",
    "blue_teleop_epa_sum",
    "blue_endgame_epa_sum",
    "blue_rp_1_epa_sum",
    "blue_rp_2_epa_sum",
    "blue_rp_3_epa_sum",
    "epa_win_prob",
    "red_rp_1_prob",
    "red_rp_2_prob",
    "red_rp_3_prob",
    "blue_rp_1_prob",
    "blue_rp_2_prob",
    "blue_rp_3_prob",
    "red_score",
    "red_auto",
    "red_teleop",
    "red_endgame",
    "red_no_fouls",
    "red_fouls",
    "blue_score",
    "blue_auto",
    "blue_teleop",
    "blue_endgame",
    "blue_no_fouls",
    "blue_fouls",
]

team_match_metrics = [
    "time",
    "year",
    "team",
    "epa",
    "auto_epa",
    "teleop_epa",
    "endgame_epa",
    "rp_1_epa",
    "rp_2_epa",
    "rp_3_epa",
]
