from typing import Dict, List

from src.constants import CURR_YEAR

key_to_name = {
    2016: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "defenses_rp",
        "rp_2": "tower_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_0": "auto_reach_points",
        "comp_1": "auto_crossing_points",
        "comp_2": "auto_low_boulders",
        "comp_3": "auto_high_boulders",
        "comp_4": "teleop_crossing_points",
        "comp_5": "teleop_low_boulders",
        "comp_6": "teleop_high_boulders",
        "comp_7": "challenge_points",
        "comp_8": "scale_points",
    },
    2017: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "rotor_rp",
        "rp_2": "kpa_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_0": "auto_mobility_points",
        "comp_1": "auto_fuel_low",
        "comp_2": "auto_fuel_high",
        "comp_3": "auto_rotor_points",
        "comp_4": "teleop_fuel_low",
        "comp_5": "teleop_fuel_high",
        "comp_6": "teleop_rotor_points",
        "comp_7": "takeoff_points",
        "comp_8": "kpa",
        "comp_9": "gears",
    },
    2018: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "auto_rp",
        "rp_2": "climb_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_0": "auto_run_points",
        "comp_1": "auto_switch_secs",
        "comp_2": "auto_scale_secs",
        "comp_3": "teleop_switch_secs",
        "comp_4": "teleop_scale_secs",
        "comp_5": "vault_points",
        "comp_6": "auto_scale_power",
        "comp_7": "switch_power",
        "comp_8": "scale_power",
        "comp_9": "opp_switch_power",
    },
    2019: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "rocket_rp",
        "rp_2": "hab_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_0": "sandstorm_points",
        "comp_1": "bay_hatch_pieces",
        "comp_2": "bay_cargo_pieces",
        "comp_3": "rocket_hatch_low_pieces",
        "comp_4": "rocket_hatch_mid_pieces",
        "comp_5": "rocket_hatch_high_pieces",
        "comp_6": "rocket_cargo_low_pieces",
        "comp_7": "rocket_cargo_mid_pieces",
        "comp_8": "rocket_cargo_high_pieces",
        "comp_9": "hab_climb_points",
    },
    2020: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "cells_rp",
        "rp_2": "climb_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_0": "auto_init_line_points",
        "comp_1": "auto_cells_bottom",
        "comp_2": "auto_cells_outer",
        "comp_3": "auto_cells_inner",
        "comp_4": "teleop_cells_bottom",
        "comp_5": "teleop_cells_outer",
        "comp_6": "teleop_cells_inner",
        "comp_7": "control_panel_points",
        "comp_8": "endgame_points",
    },
    2021: {},
    2022: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "cargo_rp",
        "rp_2": "hangar_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_0": "auto_taxi_points",
        "comp_1": "auto_cargo_lower",
        "comp_2": "auto_cargo_upper",
        "comp_3": "teleop_cargo_lower",
        "comp_4": "teleop_cargo_upper",
        "comp_5": "endgame_points",
    },
    2023: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "links_rp",
        "rp_2": "activation_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_0": "auto_charge_station_points",
        "comp_1": "auto_pieces",
        "comp_2": "teleop_grid_points",
        "comp_3": "bottom_pieces",
        "comp_4": "middle_pieces",
        "comp_5": "top_pieces",
        "comp_6": "cube_points",
        "comp_7": "cone_points",
        "comp_8": "links",
        "comp_9": "endgame_charge_station_points",
    },
    2024: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "melody_rp",
        "rp_2": "ensemble_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_0": "auto_leave_points",
        "comp_1": "auto_note_points",
        "comp_2": "teleop_note_points",
        "comp_3": "speaker_points",
        "comp_4": "amplified_notes",
        "comp_5": "endgame_park_points",
        "comp_6": "endgame_on_stage_points",
        "comp_7": "endgame_harmony_points",
        "comp_8": "endgame_trap_points",
        "comp_9": "endgame_spotlight_points",
    },
    2025: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "auto_rp",
        "rp_2": "coral_rp",
        "rp_3": "barge_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_0": "auto_coral_points",
        "comp_1": "teleop_coral_points",
        "comp_2": "coral_l1",
        "comp_3": "coral_l2",
        "comp_4": "coral_l3",
        "comp_5": "coral_l4",
        "comp_6": "processor_algae",
        "comp_7": "processor_algae_points",
        "comp_8": "net_algae_points",
        "comp_9": "barge_points",
    },
    2026: {
        "auto": "auto_points",
        "teleop": "teleop_points",
        "endgame": "endgame_points",
        "rp_1": "energized_rp",
        "rp_2": "supercharged_rp",
        "rp_3": "traversal_rp",
        "tiebreaker": "tiebreaker_points",
        "comp_0": "auto_fuel",
        "comp_1": "auto_tower",
        "comp_2": "transition_fuel",
        "comp_3": "first_shift_fuel",
        "comp_4": "second_shift_fuel",
        "comp_5": "endgame_fuel",
        "comp_6": "endgame_tower",
    },
}

# Derived fields computed from stored EPA components and added to API breakdown responses.
# Each entry maps derived_name -> list of source names to sum.
derived_breakdown: Dict[int, Dict[str, List[str]]] = {
    2024: {
        "total_note_points": ["auto_note_points", "teleop_note_points"],
    },
    2025: {
        "total_coral_points": ["auto_coral_points", "teleop_coral_points"],
        "total_algae_points": ["processor_algae_points", "net_algae_points"],
    },
    2026: {
        "teleop_fuel": [
            "transition_fuel",
            "first_shift_fuel",
            "second_shift_fuel",
            "endgame_fuel",
        ],
        "total_fuel": [
            "auto_fuel",
            "transition_fuel",
            "first_shift_fuel",
            "second_shift_fuel",
            "endgame_fuel",
        ],
        "total_tower": ["auto_tower", "endgame_tower"],
    },
}

all_keys: Dict[int, List[str]] = {}
for year in range(2002, CURR_YEAR + 1):
    if year not in key_to_name:
        all_keys[year] = ["no_foul_points"]
    else:
        all_keys[year] = [
            "no_foul_points",
            "auto_points",
            "teleop_points",
            "endgame_points",
            "rp_1",
            "rp_2",
            "rp_3",
            "tiebreaker_points",
        ]
        for i in range(0, 10):
            if f"comp_{i}" in key_to_name[year]:
                all_keys[year].append(key_to_name[year][f"comp_{i}"])
