# Generated by Django 3.0.6 on 2020-05-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('event', models.CharField(max_length=10)),
                ('elo_max', models.IntegerField()),
                ('elo_top8', models.IntegerField()),
                ('elo_top24', models.IntegerField()),
                ('elo_mean', models.IntegerField()),
                ('elo_sd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=10)),
                ('years_active', models.IntegerField()),
                ('active', models.BooleanField()),
                ('elo', models.IntegerField()),
                ('elo_mean', models.IntegerField()),
                ('elo_max', models.IntegerField()),
                ('elo_max_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('elo_max', models.IntegerField()),
                ('elo_1p', models.IntegerField()),
                ('elo_5p', models.IntegerField()),
                ('elo_10p', models.IntegerField()),
                ('elo_25p', models.IntegerField()),
                ('elo_median', models.IntegerField()),
                ('elo_mean', models.IntegerField()),
                ('elo_sd', models.IntegerField()),
                ('acc', models.DecimalField(decimal_places=4, max_digits=6)),
                ('mse', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='TeamYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('team', models.IntegerField()),
                ('elo_start', models.IntegerField()),
                ('elo_pre_champs', models.IntegerField()),
                ('elo_end', models.IntegerField()),
                ('elo_mean', models.IntegerField()),
                ('elo_max', models.IntegerField()),
                ('elo_diff', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('percentile', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
            options={
                'unique_together': {('year', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('event', models.CharField(max_length=10)),
                ('match', models.CharField(max_length=10)),
                ('team', models.IntegerField()),
                ('elo_start', models.IntegerField()),
                ('elo_end', models.IntegerField()),
                ('elo_diff', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'event', 'match', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('event', models.CharField(max_length=10)),
                ('team', models.IntegerField()),
                ('elo_start', models.IntegerField()),
                ('elo_pre_playoffs', models.IntegerField()),
                ('elo_end', models.IntegerField()),
                ('elo_mean', models.IntegerField()),
                ('elo_max', models.IntegerField()),
                ('elo_diff', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'event', 'team')},
            },
        ),
    ]
