# Generated by Django 3.0.6 on 2020-05-19 02:46

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('event', models.CharField(max_length=10)),
                ('elo_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_top8', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_top24', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_mean', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team', models.IntegerField(primary_key=True, serialize=False)),
                ('elos', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('elo_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_max_year', models.IntegerField()),
                ('elo_mean', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('elo_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_10p', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_25p', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_median', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_mean', models.DecimalField(decimal_places=2, max_digits=6)),
                ('acc', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mse', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='TeamYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('team', models.IntegerField()),
                ('elo_start', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_pre_champs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_end', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_diff', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rank', models.IntegerField()),
                ('percentile', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'unique_together': {('year', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('event', models.CharField(max_length=10)),
                ('match', models.CharField(max_length=10)),
                ('team', models.IntegerField()),
                ('start_elo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('end_elo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_diff', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'unique_together': {('year', 'event', 'match', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('event', models.CharField(max_length=10)),
                ('team', models.IntegerField()),
                ('elo_start', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_pre_playoffs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_end', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('elo_diff', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'unique_together': {('year', 'event', 'team')},
            },
        ),
    ]
