# Generated by Django 3.0.6 on 2020-05-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamevent',
            name='elo_mean',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamyear',
            name='elo_mean',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
    ]
