# Generated by Django 3.0.6 on 2020-05-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_auto_20200518_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='elo_sd',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='year',
            name='elo_1p',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='year',
            name='elo_5p',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='year',
            name='elo_sd',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
            preserve_default=False,
        ),
    ]
