# Generated by Django 3.0.6 on 2020-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_auto_20200520_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamevent',
            name='time',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammatch',
            name='time',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
