# Generated by Django 3.0.6 on 2020-05-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_auto_20200519_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammatch',
            old_name='end_elo',
            new_name='elo_end',
        ),
        migrations.RenameField(
            model_name='teammatch',
            old_name='start_elo',
            new_name='elo_start',
        ),
    ]
