# Generated by Django 3.0.6 on 2020-05-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_auto_20200521_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teamyear',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
