# Generated by Django 3.0.6 on 2020-05-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_team_elo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='acc',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='year',
            name='mse',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
