# Generated by Django 3.0.6 on 2020-05-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0007_auto_20200519_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammatch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
