# Generated by Django 3.0.6 on 2020-05-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_auto_20200519_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamyear',
            name='percentile',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
