# Generated by Django 3.0.6 on 2020-05-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0010_auto_20200520_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='elos',
        ),
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='district',
            field=models.CharField(default='fill in', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='fill in', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='state',
            field=models.CharField(default='fill in', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='years_active',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
