# Generated by Django 3.0.6 on 2020-05-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0011_auto_20200520_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='state',
        ),
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
