service: default
runtime: python38
entrypoint: gunicorn -w 1 -t 600 -k uvicorn.workers.UvicornWorker main:app

instance_class: F2

# up to 4 instance
automatic_scaling:
  min_instances: 4
  max_instances: 16

#set to minimums
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  LOCAL_DB: false
