service: default
runtime: python311
entrypoint: gunicorn -w 1 -t 600 -k uvicorn.workers.UvicornWorker main:app

instance_class: F4

automatic_scaling:
  min_instances: 1
  max_instances: 4

env_variables:
  LOCAL_DB: false
