service: default
runtime: python311
entrypoint: gunicorn -w 1 -t 600 -k uvicorn.workers.UvicornWorker main:app

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2

env_variables:
  LOCAL_DB: false
