steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
    dir: "backend"
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    dir: "backend"
    env:
      - "CRDB_USER=abhijit"
      - "CRDB_PWD=${_CRDB_PWD}"
      - "CRDB_HOST=statbotics-5256.5xj.gcp-us-central1.cockroachlabs.cloud:26257"
      - "PROD=True"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--appyaml", "./deploy/site_app.yaml"]
    dir: "backend"
