service: data-v3
runtime: python38
entrypoint: gunicorn -w 1 -t 600 -k uvicorn.workers.UvicornWorker main:app

instance_class: B4

# exactly one instance
basic_scaling:
  max_instances: 1

#set to minimums
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  LOCAL_DB: false
